export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_RESET_REDUCER = 'AUTH_RESET_REDUCER';
export const AUTH_SIGNUP = 'AUTH_SIGNUP'

export const EXPENSE_CATEGORIES_ADD = 'EXPENSE_CATEGORIES_ADD';

export const EXPENSES_ADD_EXPENSE = 'EXPENSES_ADD_EXPENSE';
export const EXPENSES_SAVE_EXPENSE = 'EXPENSES_SAVE_EXPENSE';